INSERT INTO `tools` (`tool_id`, `tool_name`, `tool_size`, `tool_type`, `current_status`, `total_quantity`, `available_quantity`, `consumed_quantity`, `trained`) VALUES
(1, 'Adjustable Wrench', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(2, 'Allen Key', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(3, 'Box Cutter', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(4, 'Breadboard', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(5, 'Caliper', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(6, 'Channel Lock', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(7, 'File', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(8, 'Hot Glue Gun', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(9, 'Multimeter', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(10, 'Plier', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(11, 'Safety Glasses', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(12, 'Scissors', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(13, 'Screwdriver', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1),
(14, 'Super Glue', 'onesize', 'consumable', 'Available', 5, 5, 0, 1),
(15, 'Tape Measure', 'onesize', 'Borrowable', 'Available', 5, 5, 0, 1);